services:
  traveling_salesman_problem:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
